const INCENTIVES_DB = [
  {
    'AFUE': null,
    'amount': '$600',
    'capacity': null,
    'compressor_type': null,
    'COP': null,
    'display_name': '25C - Central AC',
    'display_text': 'Federal Tax Credit for AC (next year)',
    'EER2': '12.00',
    'energy_source': null,
    'entity_name': 'IRS',
    'existing_system_age': null,
    'Existing_system_required': 'FALSE',
    'HSPF2': null,
    'HVAC_system_type': 'Split',
    'incentives_id': '13f004d8-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '16.00',
    'tonnage': null,
    'ventilation_type': null,
  },
  {
    'AFUE': '0.97',
    'amount': '$600',
    'capacity': null,
    'compressor_type': null,
    'COP': null,
    'display_name': '25C - Central AC',
    'display_text': 'Federal Tax Credit for Furnace (next year)',
    'EER2': null,
    'energy_source': null,
    'entity_name': 'IRS',
    'existing_system_age': null,
    'Existing_system_required': 'FALSE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f00654-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'furnace',
    'region': null,
    'SEER2': null,
    'tonnage': null,
    'ventilation_type': null,
  },
  {
    'AFUE': null,
    'amount': '$250',
    'capacity': null,
    'compressor_type': 'Conventional',
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': '12',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': '10',
    'Existing_system_required': 'TRUE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f00668-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '15.2',
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'amount': '$150',
    'capacity': null,
    'compressor_type': 'Inverter',
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': '12',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': '10',
    'Existing_system_required': 'TRUE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f00690-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '15.2',
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'amount': '$350',
    'capacity': null,
    'compressor_type': null,
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': '13',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': '10',
    'Existing_system_required': 'TRUE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f006a4-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '16',
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'amount': '$450',
    'capacity': null,
    'compressor_type': 'Conventional',
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': '13',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': '10',
    'Existing_system_required': 'TRUE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f006ae-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '18',
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': null,
    'amount': '$550',
    'capacity': null,
    'compressor_type': 'Inverter',
    'COP': null,
    'display_name': 'Austin Energy - Central AC',
    'display_text': 'Austin Energy Rebate (instant)',
    'EER2': '13',
    'energy_source': 'electricity',
    'entity_name': 'Austin Energy',
    'existing_system_age': '10',
    'Existing_system_required': 'TRUE',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f006c2-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'central_ac',
    'region': null,
    'SEER2': '18',
    'tonnage': null,
    'ventilation_type': 'ducted',
  },
  {
    'AFUE': '0.92',
    'amount': '$675',
    'capacity': null,
    'compressor_type': null,
    'COP': null,
    'display_name': 'Texas Gas - Furnace',
    'display_text': 'Texas Gas (instant)',
    'EER2': null,
    'energy_source': 'natural_gas',
    'entity_name': 'Texas Gas',
    'existing_system_age': '',
    'Existing_system_required': '',
    'HSPF2': null,
    'HVAC_system_type': null,
    'incentives_id': '13f006cc-bdd1-11ed-9a5f-3aebb006c675',
    'product_type': 'furnace',
    'region': null,
    'SEER2': null,
    'tonnage': null,
    'ventilation_type': null,
  },
]
export {INCENTIVES_DB}

